version: '2'
services:
  server:
    build:
      context: .
      dockerfile: DockerfileServer
    ports:
      - 3001:3001
    environment:
      DEBUG: 'true'
      PORT: '3001'
      DB_DATABASE: 'blogger'
      DB_USER: 'postgres'
      DB_PASS: 'P@$$w0rd'
      DB_SERVER: 'db'
      DB_PORT: '5432'

  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'blogger'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'P@$$w0rd'
